# Generated by Django 5.2.18 on 2026-10-06 17:50

from django.conf import settings
from django.db import migrations, models


def keep_latest_review(apps, schema_editor):
    """Before the unique constraint: if someone reviewed a product twice, keep the newest."""
    ReviewRating = apps.get_model('store', 'ReviewRating')
    seen = set()
    for review in ReviewRating.objects.order_by('user_id', 'product_id', '-updated_at', '-id'):
        key = (review.user_id, review.product_id)
        if key in seen:
            review.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_compare_at_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(keep_latest_review, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reviewrating',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='one_review_per_user_and_product'),
        ),
    ]
