# Generated by Django 5.2.7 on 2025-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
